# 网站的基本信息
site:
  tab: ZSXの小站 # 浏览器标签栏上显示的文本
  title: ZSXの小站 # 网站的标题
  description: 钟神秀的博客，我在这里记录我的生活日常、踩坑记录和资源分享。 # 网站的描述，用于SEO等
  language: zh  # 网站的语言，例如 "en" 是英文
  favicon: /favicon.ico # 网站的图标，用于浏览器标签栏和其他地方显示
  theme: # 更多主题 https://daisyui.com/docs/themes/
    light: winter # 主题的浅色模式
    dark: dracula # 主题的深色模式
    code: github-dark-dimmed # 代码块的主题 https://shiki.style/themes
  date_format: ddd MMM DD YYYY # 日期格式设置，支持自定义格式
  blog: # 博客相关配置
    pageSize: 8 # 每页显示的文章数量
  banner:  
    images:  
      - "/image/banner/1.webp"  
      - "/image/banner/2.webp"  
      - "/image/banner/3.webp"  
 
    height: "60vh"
  # Banner 页面标题配置
  pages:
    home:  
      title: "欢迎来到ZSXの小站！"  
      subtitle: "造化钟神秀，阴阳割昏晓！"   
      typewriterTexts: # 新增打字机文本配置  
        - "愿你看清一切真相后，依旧热爱你的家人和朋友。"  
        - "总有些事情，高于其他！"  
        - "少年曾许凌云志，曾许人间第一流！"  
        - "每一段旅行，都有终点~" 
    music:
      title: 音乐盒子
      subtitle: 随节奏，慢下来
    friend:  
      title: "友人帐"  
      subtitle: "记录那些珍贵的友谊，分享彼此的故事"  
    about:  
      title: "About Me"  
      subtitle: "一个摆烂的牛马~" 
    navigation:  
      title: "网站导航"  
      subtitle: "收藏的常用网站和工具链接"  
    anime:
      title: "追番"  
      subtitle: "记录和分享我喜欢的动漫作品"
    project:  
      title: "Projects"  
      subtitle: "展示一些个人搭建的项目，搬运工！"
  menu: # 菜单配置
    - id: home # 菜单项的唯一标识符
      text: 首页 # 菜单项显示的文本
      href: / # 菜单项链接的地址
      svg: "material-symbols:home-outline-rounded"
      target: _self
    - id: navigation  
      text: 导航  
      href: /navigation  
      svg: "material-symbols:explore-outline"  
      target: _self
    - id: friend
      text: 友人帐
      href: /links
      svg: "material-symbols:supervisor-account-outline-rounded"
      target: _self
    # - id: blog
    #   text: 博客
    #   href: /blog
    #   svg: "material-symbols:book-2-outline-rounded"
    #   target: _self
      # subItems:
      #   - id: all
      #     text: All
      #     href: /blog
      #     svg: "material-symbols:ink-pen-outline-rounded"
      #     target: _self
      #   - id: course
      #     text: 教程
      #     href: /blog/category/Course
      #     svg: "material-symbols:book-outline"
      #     target: _self
      #   - id: anime  
      #     text: 动漫  
      #     href: /blog/category/Anime  
      #     svg: "material-symbols:movie-outline"  
      #     target: _self 
      #   - id: tv  
      #     text: TV  
      #     href: /blog/category/TV  
      #     svg: "material-symbols:movie-outline"  
      #     target: _self 
      #   - id: documentation
      #     text: 文章
      #     href: /blog/category/Documentation
      #     svg: "material-symbols:unknown-document-outline-rounded"
      #     target: _self
        # - id: examples
        #   text: Examples
        #   href: /blog/category/Examples
        #   svg: "material-symbols:deployed-code-outline"
        #   target: _self
        # 子菜单项配置
    - id: page
      text: 我的
      href: #
      svg: "mdi:web"
      target: _self
      subItems:
        - id: about
          text: 关于
          href: /mcyzsx
          svg: "material-symbols:info-outline-rounded"
          target: _self
        - id: anime
          text: 追番
          href: /anime
          svg: "material-symbols:movie-outline" 
          target: _self
        - id: diary
          text: 日记
          href: /diary
          svg: "arcticons:diary" 
          target: _self
        - id: project
          text: 项目
          href: /project
          svg: "material-symbols:code-blocks-outline"
          target: _self
        - id: albums
          text: 相册
          href: /albums
          svg: "heroicons:photo"
          target: _self
        - id: sponsors
          text: 赞助
          href: /sponsors
          svg: "simple-icons:githubsponsors"
          target: _self
        - id: steam
          text: Steam
          href: /steam
          svg: "mdi:steam"
          target: _self
        - id: message
          text: 留言板
          href: /message
          svg: "mdi:message"
          target: _self
        - id: music
          text: 音乐馆
          href: /music
          svg: "mdi:music"
          target: _self
        - id: device
          text: 我的装备
          href: /device
          svg: "material-symbols:devices-other-outline-rounded"
          target: _self
        - id: news
          text: 每天60S
          href: /news
          svg: "lucide:newspaper"
          target: _self
        - id: weather
          text: 实时天气
          href: /weather
          svg: "meteocons:fog-day-fill"
          target: _self
    # - id: contact
    #   text: 联系
    #   href: /contact
    #   svg: "material-symbols:contact-mail-outline-rounded"
    #   target: _self
    #   subItems:
    # - id: contact
    #   text: Contact
    #   href: "mailto:contact.evesunmaple@outlook.com"
    #   target: _blank # 在新标签页打开
    #   svg: "material-symbols:attach-email-outline-rounded"
    - id: trevel
      text: 开往
      href: https://www.travellings.cn/go.html
      svg: "mdi:subway"
      target: _blank

# 用户的个人信息
user:
  name: 钟神秀 # 用户名
  site: "https://boke.zsx815.top/" # 用户的网站链接
  avatar: /profile.png # 用户头像路径
  sidebar: # 侧边栏配置
    social:
      # - href: "https://afdian.com/a/saroprock" # 链接
      #   ariaLabel: Support my work # 图标的可访问性标签
      #   title: Support my work # 图标的悬浮标题
      #   svg: "ri:cup-line"
      - href: "https://github.com/zsxcoder"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://space.bilibili.com/396923563"
        ariaLabel: BiliBili
        title: BiliBili
        svg: "ri:bilibili-line"
      - href: "https://x.com/kemiao"
        ariaLabel: X(twitter)
        title: X(twitter)
        svg: "ri:twitter-line"
      - href: "https://t.me/KemiaoJun"
        ariaLabel: Telegram
        title: Telegram
        svg: "ri:telegram-line"
      - href: "mailto:me@mcyzsx.top"
        ariaLabel: Mail
        title: Mail
        svg: "material-symbols:mail"
      - href: "https://qm.qq.com/q/Ha1GZQtMgE"
        ariaLabel: QQ
        title: QQ
        svg: "ri:qq-fill"
      # - href: "https://app.folo.is/share/feeds/172229198194932736"  
      #   ariaLabel: Subscribe via Folo  
      #   title: Folo  
      #   svg: "ri:rss-fill"

  footer:
    social:
      # - href: "https://afdian.com/a/saroprock" # 链接
      #   ariaLabel: Support my work # 图标的可访问性标签
      #   title: Support my work # 图标的悬浮标题
      #   svg: "ri:cup-line"
      - href: "https://github.com/zsxcoder"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://space.bilibili.com/396923563"
        ariaLabel: BiliBili
        title: BiliBili
        svg: "ri:bilibili-line"
      - href: "https://x.com/kemiao"
        ariaLabel: X(twitter)
        title: X(twitter)
        svg: "ri:twitter-line"
      - href: "https://t.me/KemiaoJun"
        ariaLabel: Telegram
        title: Telegram
        svg: "ri:telegram-line"
      - href: "mailto:me@mcyzsx.top"
        ariaLabel: Mail
        title: Mail
        svg: "material-symbols:mail"
      - href: "https://qm.qq.com/q/Ha1GZQtMgE"
        ariaLabel: QQ
        title: QQ
        svg: "ri:qq-fill"

# 评论系统配置
comments:
  enable: true # 是否启用评论
  type: waline # giscus/waline/none
  giscus:
    repo: "xz131714/gsc"
    repoId: "R_kgDOPTM-mA"
    category: "General"
    categoryId: "DIC_kwDOPTM-mM4CtcFq"
    mapping: "pathname"
    lang: "zh-CN"
    inputPosition: "top"
    reactionsEnabled: "1"
    emitMetadata: "0"
    loading: "lazy"
  waline:
    serverURL: "https://ryuchan-comment.zsx815.top"
    lang: "zh-CN"
    emoji:
      - "https://unpkg.com/@waline/emojis@1.1.0/weibo"
      - "https://unpkg.com/@waline/emojis@1.1.0/bilibili"
    meta: ["nick", "mail", "link"]
    requiredMeta: []
    reaction: false
    pageview: false
# Umami 统计配置
umami:
  enable: true
  baseUrl: "https://umami.mcyzsx.top"
  shareId: "CYRk95cHwlWkyqqE"
  websiteId: "ce811557-6832-478a-b2b4-83c2a5df0d8e"
  timezone: "Asia/Shanghai"

